export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  VERIFY_OTP: "/verify-otp",
  FORGOT_PASSWORD: "/forgot-password", // placeholder route path
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    CLIENTS: "/admin/clients",
    KYC_VERIFICATION: "/admin/kyc-verification",
    PARTNERS: "/admin/partners",
    EXCHANGE_SETUP: "/admin/exchange-setup",
    COPY_TRADING: "/admin/copy-trading",
    PLAN_MANAGEMENT: "/admin/plan-management",
    BILLING_CYCLES: "/admin/billing-cycles",
    INVOICING: "/admin/invoicing",
    TRANSACTION_LOGS: "/admin/transaction-logs",
    PNL_ANALYTICS: "/admin/pnl-analytics",
    PERFORMANCE_METRICS: "/admin/performance-metrics",
    PARTNER_PERFORMANCE: "/admin/partner-performance",
    TICKETS: "/admin/tickets",
    LIVE_CHAT: "/admin/live-chat",
    HELP_CENTER: "/admin/help-center",
    USER_GUIDELINES: "/admin/user-guidelines",
    FAQS: "/admin/faqs",
    USER_ROLES: "/admin/user-roles",
    ADMIN_SECURITY: "/admin/admin-security",
    AUDIT_LOGS: "/admin/audit-logs",
    NOTIFICATION_TEMPLATES: "/admin/notification-templates",
  },
  CLIENT: {
    DASHBOARD: "/client/dashboard",
    PROFILE: "/client/profile",
    EXCHANGE_SETUP: "/client/exchange-setup",
    SUBSCRIPTION: "/client/subscription",
    PNL_ANALYTICS: "/client/pnl-analytics",
    INVOICES: "/client/invoices",
    SUPPORT: "/client/support",
    BECOME_PARTNER: "/client/become-partner",
  },
} as const;
