export const TITLES: Record<string, string> = {
  "/admin/dashboard": "Dashboard",
  "/admin/clients": "Client Directory",
  "/admin/kyc-verification": "KYC Verification",
  "/admin/partners": "Partners",
  "/admin/exchange-setup": "Exchange Setup",
  "/admin/copy-trading": "Copy Trading",
  "/admin/plan-management": "Plan Management",
  "/admin/billing-cycles": "Billing Cycles (TraaS)",
  "/admin/invoicing": "Invoicing",
  "/admin/transaction-logs": "Transaction Logs",
  "/admin/pnl-analytics": "P&L Analytics",
  "/admin/performance-metrics": "Performance Metrics",
  "/admin/partner-performance": "Partner Performance",
  "/admin/tickets": "Ticket Management",
  "/admin/masters": "Master Accounts",
  "/admin/invoices": "Invoices",
  "/admin/live-chat": "Live Chat",
  "/admin/help-center": "Help Center",
  "/admin/user-guidelines": "User Guidelines",
  "/admin/faqs": "FAQs",
  "/admin/user-roles": "User & Role Mgmt",
  "/admin/admin-security": "Admin Security (2FA)",
  "/admin/audit-logs": "Audit Logs",
  "/admin/notification-templates": "Notification Templates",
  "/client/dashboard": "Dashboard",
  "/client/profile": "My Profile",
  "/client/exchange-setup": "Exchange Setup",
  "/client/subscription": "My Subscription",
  "/client/pnl-analytics": "P&L Analytics",
  "/client/invoices": "Invoices",
  "/client/support": "Support",
  "/client/become-partner": "Become a Partner",
};
